spring:
  jpa:
    hibernate:
      ddl-auto: update


  datasource:
      url: jdbc:postgresql://localhost:5432/api-eletrical-equipament-monitor-altura?useTimezone=true&serverTimezone=UTC
      username: ${username}
      password: ${password}
      driver-class-name: org.postgresql.Driver
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      properties:
        hibernate:
        format_sql: true