spring:
  jpa:
    hibernate:
#      generate-ddl: false
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/api-eletrical-equipment-monitor-altura?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${username}
    password: ${password}
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
