spring:

  #Habilita lançamento de exceptions NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #Configuração do flyway
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  #Configuração do Jackson para habilitar lançamento de exceptions conforme atributos abaixo
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  profiles:
    active: ${PROD_PROFILE:dev}
  output:
    ansi:
      enabled: ALWAYS