spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api-eletrical-equipament-monitor-altura
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        ddl-auto: create
